### ISSUE TITLE
bugs: Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by Carefree-happy** [zh-lx/mini-react#7]
mini-react main分支 
二：2根据 React.element 创建 dom
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

**Comment by zh-lx** [comment]
> 

看下你的dom结构是什么样子呢

**Comment by zh-lx** [comment]
感谢反馈，代码有点问题已修改

**Comment by kitiho** [comment]
appendchild改成append readme可以修改一下
